import { requestBinary, requestJson } from './backendClient';
import type { ConversationRuntimeDiagnostics } from '../types/backend';

interface RawDirectConversationResponse {
  session_id: string;
  conversation_status: string;
  response: string;
  runtime?: ConversationRuntimeDiagnostics | null;
}

export interface DirectConversationResponse extends RawDirectConversationResponse {
  runtime: ConversationRuntimeDiagnostics | null;
  request_id: string;
}

/**
 * Single game-facing conversation call. The backend owns session resolution,
 * memory/context, knowledge retrieval, response generation, and turn persistence.
 * No session_id or response-mode flag is sent by the UI.
 */
export function sendDirectConversation(
  bearerToken: string,
  characterExternalId: string,
  actorExternalId: string,
  message: string,
  signal?: AbortSignal,
): Promise<DirectConversationResponse> {
  const requestId = crypto.randomUUID();
  return requestJson<RawDirectConversationResponse>('/v1/conversation', {
    method: 'POST',
    bearerToken,
    body: {
      character_external_id: characterExternalId,
      actor_external_id: actorExternalId,
      message: message.trim(),
    },
    extraHeaders: {
      // Development UI diagnostics are opt-in; production game clients can
      // simply omit this header and receive the minimal public response.
      'X-Diagnostics': 'true',
    },
    signal,
    requestId,
  }).then((raw) => ({
    ...raw,
    runtime: raw.runtime ?? null,
    request_id: requestId,
  }));
}


/**
 * Fetches the binary voice generated by Convai for the exact conversation
 * request. The request ID is the same ID sent on POST /v1/conversation, so
 * concurrent turns cannot return the wrong audio.
 */
export function getConversationAudio(
  bearerToken: string,
  requestId: string,
  signal?: AbortSignal,
): Promise<ArrayBuffer> {
  return requestBinary(`/v1/conversation/audio/${encodeURIComponent(requestId)}`, {
    method: 'GET',
    bearerToken,
    requestId,
    signal,
  });
}
